# This is a basic workflow to help you get started with Actions

name: dev_card
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  dev_card:
    runs-on: ubuntu-latest
    steps:
      - name: dev_card
        uses: dailydotdev/action-devcard@2.0.4
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          
